version: 2.1

executors:
  default-executor:
    docker:
      - image: cypress/base:10

jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-deps-{{ checksum "yarn.lock" }}
            - v2-deps

      - run:
          name: 'Install dependencies'
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v2-deps-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths: .

  check-prettier:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run prettier check on project files'
          command: yarn prettier:check

  check-linter:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run linter'
          command: yarn lint

  run-unit-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run unit tests'
          command: yarn test:unit

  run-e2e-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "yarn.lock" }}
            - v2-deps
      - run:
          name: 'Run e2e tests'
          command: echo "FIXME get working"
          # command: yarn test:e2e:headless

  build-prod:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Write env var overrides'
          # we need to escape (\) the << otherwise CircleCI complains
          command: |
            theFile=.env.local
            cat \<<EOF > $theFile
            VUE_APP_INAT_BASE_URL=${PROD_INAT_BASE_URL:?}
            VUE_APP_INAT_STATIC_BASE_URL=${PROD_INAT_STATIC_BASE_URL:?}
            VUE_APP_API_BASE_URL=${PROD_API_BASE_URL:?}
            VUE_APP_OAUTH_APP_ID=${PROD_OAUTH_APP_ID:?}
            VUE_APP_OAUTH_REDIRECT_URI=${PROD_OAUTH_REDIRECT_URI:?}
            VUE_APP_INAT_PROJECT_SLUG=${PROD_INAT_PROJECT_SLUG:?}
            VUE_APP_TARGET_TAXA_ID=${PROD_TARGET_TAXA_ID:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY=${PROD_OBS_FIELD_ID_ACCURACY:?}
            VUE_APP_OBS_FIELD_ID_COUNT=${PROD_OBS_FIELD_ID_COUNT:?}
            VUE_APP_OBS_FIELD_ID_ORCHID_TYPE=${PROD_OBS_FIELD_ID_ORCHID_TYPE:?}
            VUE_APP_OBS_FIELD_ID_HOST_TREE=${PROD_OBS_FIELD_ID_HOST_TREE:?}
            VUE_APP_OBS_FIELD_ID_EPIPHYTE_HEIGHT=${PROD_OBS_FIELD_ID_EPIPHYTE_HEIGHT:?}
            VUE_APP_DEPLOYED_ENV_IS_PROD=true
            VUE_APP_GMAPS_API_KEY=${GMAPS_API_KEY:?}
            VUE_APP_SENTRY_DSN=${SENTRY_DSN:?}
            EOF
            # now some optional items
            [ ! -z $PROD_OBS_FIELD_DEFAULT_ACCURACY ] && {
              echo "VUE_APP_OBS_FIELD_DEFAULT_ACCURACY=$PROD_OBS_FIELD_DEFAULT_ACCURACY" >> $theFile
            }
            [ ! -z $PROD_OBS_FIELD_DEFAULT_ORCHID_TYPE ] && {
              echo "VUE_APP_OBS_FIELD_DEFAULT_ORCHID_TYPE=$PROD_OBS_FIELD_DEFAULT_ORCHID_TYPE" >> $theFile
            }
            [ ! -z $PROD_OBS_FIELD_ORCHID_TYPE_EPIPHYTE ] && {
              echo "VUE_APP_OBS_FIELD_ORCHID_TYPE_EPIPHYTE=$PROD_OBS_FIELD_ORCHID_TYPE_EPIPHYTE" >> $theFile
            }
            echo '[INFO] contents of .env.local'
            cat .env.local
      - run:
          name: 'Build'
          command: ./scripts/build-and-sentry-release.sh
      - persist_to_workspace: # FIXME only need dist/ right?
          root: .
          paths: .

  build-dev:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Write env var overrides'
          # we need to escape (\) the << otherwise CircleCI complains
          command: |
            theFile=.env.local
            cat \<<EOF > $theFile
            VUE_APP_INAT_BASE_URL=${DEV_INAT_BASE_URL:?}
            VUE_APP_INAT_STATIC_BASE_URL=${DEV_INAT_STATIC_BASE_URL:?}
            VUE_APP_API_BASE_URL=${DEV_API_BASE_URL:?}
            VUE_APP_OAUTH_APP_ID=${DEV_OAUTH_APP_ID:?}
            VUE_APP_OAUTH_REDIRECT_URI=${DEV_OAUTH_REDIRECT_URI:?}
            VUE_APP_INAT_PROJECT_SLUG=${DEV_INAT_PROJECT_SLUG:?}
            VUE_APP_TARGET_TAXA_ID=${DEV_TARGET_TAXA_ID:?}
            VUE_APP_OBS_FIELD_ID_ACCURACY=${DEV_OBS_FIELD_ID_ACCURACY:?}
            VUE_APP_OBS_FIELD_ID_COUNT=${DEV_OBS_FIELD_ID_COUNT:?}
            VUE_APP_OBS_FIELD_ID_ORCHID_TYPE=${DEV_OBS_FIELD_ID_ORCHID_TYPE:?}
            VUE_APP_OBS_FIELD_ID_HOST_TREE=${DEV_OBS_FIELD_ID_HOST_TREE:?}
            VUE_APP_OBS_FIELD_ID_EPIPHYTE_HEIGHT=${DEV_OBS_FIELD_ID_EPIPHYTE_HEIGHT:?}
            VUE_APP_DEPLOYED_ENV_IS_PROD=false
            VUE_APP_GMAPS_API_KEY=${GMAPS_API_KEY:?}
            VUE_APP_SENTRY_DSN=${SENTRY_DSN:?}
            EOF
            # now some optional items
            [ ! -z $DEV_OBS_FIELD_DEFAULT_ACCURACY ] && {
              echo "VUE_APP_OBS_FIELD_DEFAULT_ACCURACY=$DEV_OBS_FIELD_DEFAULT_ACCURACY" >> $theFile
            }
            [ ! -z $DEV_OBS_FIELD_DEFAULT_ORCHID_TYPE ] && {
              echo "VUE_APP_OBS_FIELD_DEFAULT_ORCHID_TYPE=$DEV_OBS_FIELD_DEFAULT_ORCHID_TYPE" >> $theFile
            }
            [ ! -z $DEV_OBS_FIELD_ORCHID_TYPE_EPIPHYTE ] && {
              echo "VUE_APP_OBS_FIELD_ORCHID_TYPE_EPIPHYTE=$DEV_OBS_FIELD_ORCHID_TYPE_EPIPHYTE" >> $theFile
            }
            echo '[INFO] contents of .env.local'
            cat .env.local
      - run:
          name: 'Build'
          command: ./scripts/build-and-sentry-release.sh
      - persist_to_workspace: # FIXME only need dist/ right?
          root: .
          paths: .

  deploy-prod:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy prod'
          command: |
            : ${FIREBASE_TOKEN:?}
            yarn firebase:deploy:ci prod

  deploy-dev:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy dev'
          command: |
            : ${FIREBASE_TOKEN:?}
            yarn firebase:deploy:ci dev

workflows:
  version: 2
  build-and-deploy-prod:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: master # dependent jobs are controlled by this
      - check-prettier:
          requires:
            - install-dependencies
      - check-linter:
          requires:
            - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - run-e2e-tests:
          requires:
            - install-dependencies
      - build-prod:
          requires:
            - check-prettier
            - check-linter
            - run-unit-tests
            - run-e2e-tests
      - deploy-prod:
          requires:
            - build-prod

  build-everything-and-deploy-dev:
    jobs:
      - install-dependencies:
          filters:
            branches:
              ignore: master # dependent jobs are controlled by this
      - check-prettier:
          requires:
            - install-dependencies
      - check-linter:
          requires:
            - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - run-e2e-tests:
          requires:
            - install-dependencies
      - build-dev:
          requires:
            - check-prettier
            - check-linter
            - run-unit-tests
            - run-e2e-tests
          filters:
            branches:
              only: develop # only build and deploy this branch
      - deploy-dev:
          requires:
            - build-dev
